import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import ConnectWallet from "@/components/ConnectWallet";
import TransferEther from "@/components/TransferEther";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <h1>My Ethereum Wallet App</h1>
      <ConnectWallet />
      <TransferEther />
    </div>
    </>
  )
}
